/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VcardShortIdRouteImport } from './routes/vcard.$shortId'
import { Route as RShortIdRouteImport } from './routes/r.$shortId'
import { Route as QShortIdRouteImport } from './routes/q.$shortId'
import { Route as ProofIdRouteImport } from './routes/proof.$id'
import { Route as PontoShortIdRouteImport } from './routes/ponto.$shortId'
import { Route as LinksShortIdRouteImport } from './routes/links.$shortId'
import { Route as FShortIdRouteImport } from './routes/f.$shortId'
import { Route as AiShortIdRouteImport } from './routes/ai.$shortId'
import { Route as AuthenticatedSubmissionsRouteImport } from './routes/_authenticated/submissions'
import { Route as AuthenticatedProofsRouteImport } from './routes/_authenticated/proofs'
import { Route as AuthenticatedPontoRouteImport } from './routes/_authenticated/ponto'
import { Route as AuthenticatedPlansRouteImport } from './routes/_authenticated/plans'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCreateRouteImport } from './routes/_authenticated/create'
import { Route as AuthenticatedBulkRouteImport } from './routes/_authenticated/bulk'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as ApiPublicVerifyPasswordRouteImport } from './routes/api/public/verify-password'
import { Route as ApiPublicSubmitRouteImport } from './routes/api/public/submit'
import { Route as ApiPublicScanaiRouteImport } from './routes/api/public/scanai'
import { Route as ApiPublicScanRouteImport } from './routes/api/public/scan'
import { Route as ApiPontoResolvePinRouteImport } from './routes/api/ponto/resolve-pin'
import { Route as ApiPontoPunchRouteImport } from './routes/api/ponto/punch'
import { Route as ApiMpWebhookRouteImport } from './routes/api/mp/webhook'
import { Route as ApiMpSubscriptionRouteImport } from './routes/api/mp/subscription'
import { Route as ApiMpSubscribeRouteImport } from './routes/api/mp/subscribe'
import { Route as ApiMpPixCheckoutRouteImport } from './routes/api/mp/pix-checkout'
import { Route as ApiAiChatRouteImport } from './routes/api/ai/chat'
import { Route as AuthenticatedFlowBuilderQrIdRouteImport } from './routes/_authenticated/flow-builder.$qrId'
import { Route as AuthenticatedCheckoutPlanSlugRouteImport } from './routes/_authenticated/checkout.$planSlug'
import { Route as AuthenticatedAnalyticsQrIdRouteImport } from './routes/_authenticated/analytics.$qrId'
import { Route as AuthenticatedAdminPlansRouteImport } from './routes/_authenticated/admin.plans'
import { Route as AuthenticatedAdminAiRouteImport } from './routes/_authenticated/admin.ai'
import { Route as ApiPontoWebauthnRegisterVerifyRouteImport } from './routes/api/ponto/webauthn/register-verify'
import { Route as ApiPontoWebauthnRegisterOptionsRouteImport } from './routes/api/ponto/webauthn/register-options'
import { Route as ApiPontoWebauthnAuthVerifyRouteImport } from './routes/api/ponto/webauthn/auth-verify'
import { Route as ApiPontoWebauthnAuthOptionsRouteImport } from './routes/api/ponto/webauthn/auth-options'
import { Route as ApiPontoAdminWebauthnClearRouteImport } from './routes/api/ponto/admin/webauthn-clear'
import { Route as ApiPontoAdminDeviceResetRouteImport } from './routes/api/ponto/admin/device-reset'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VcardShortIdRoute = VcardShortIdRouteImport.update({
  id: '/vcard/$shortId',
  path: '/vcard/$shortId',
  getParentRoute: () => rootRouteImport,
} as any)
const RShortIdRoute = RShortIdRouteImport.update({
  id: '/r/$shortId',
  path: '/r/$shortId',
  getParentRoute: () => rootRouteImport,
} as any)
const QShortIdRoute = QShortIdRouteImport.update({
  id: '/q/$shortId',
  path: '/q/$shortId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofIdRoute = ProofIdRouteImport.update({
  id: '/proof/$id',
  path: '/proof/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PontoShortIdRoute = PontoShortIdRouteImport.update({
  id: '/ponto/$shortId',
  path: '/ponto/$shortId',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksShortIdRoute = LinksShortIdRouteImport.update({
  id: '/links/$shortId',
  path: '/links/$shortId',
  getParentRoute: () => rootRouteImport,
} as any)
const FShortIdRoute = FShortIdRouteImport.update({
  id: '/f/$shortId',
  path: '/f/$shortId',
  getParentRoute: () => rootRouteImport,
} as any)
const AiShortIdRoute = AiShortIdRouteImport.update({
  id: '/ai/$shortId',
  path: '/ai/$shortId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSubmissionsRoute =
  AuthenticatedSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProofsRoute = AuthenticatedProofsRouteImport.update({
  id: '/proofs',
  path: '/proofs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPontoRoute = AuthenticatedPontoRouteImport.update({
  id: '/ponto',
  path: '/ponto',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlansRoute = AuthenticatedPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCreateRoute = AuthenticatedCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBulkRoute = AuthenticatedBulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicVerifyPasswordRoute = ApiPublicVerifyPasswordRouteImport.update({
  id: '/api/public/verify-password',
  path: '/api/public/verify-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSubmitRoute = ApiPublicSubmitRouteImport.update({
  id: '/api/public/submit',
  path: '/api/public/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicScanaiRoute = ApiPublicScanaiRouteImport.update({
  id: '/api/public/scanai',
  path: '/api/public/scanai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicScanRoute = ApiPublicScanRouteImport.update({
  id: '/api/public/scan',
  path: '/api/public/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPontoResolvePinRoute = ApiPontoResolvePinRouteImport.update({
  id: '/api/ponto/resolve-pin',
  path: '/api/ponto/resolve-pin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPontoPunchRoute = ApiPontoPunchRouteImport.update({
  id: '/api/ponto/punch',
  path: '/api/ponto/punch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMpWebhookRoute = ApiMpWebhookRouteImport.update({
  id: '/api/mp/webhook',
  path: '/api/mp/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMpSubscriptionRoute = ApiMpSubscriptionRouteImport.update({
  id: '/api/mp/subscription',
  path: '/api/mp/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMpSubscribeRoute = ApiMpSubscribeRouteImport.update({
  id: '/api/mp/subscribe',
  path: '/api/mp/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMpPixCheckoutRoute = ApiMpPixCheckoutRouteImport.update({
  id: '/api/mp/pix-checkout',
  path: '/api/mp/pix-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFlowBuilderQrIdRoute =
  AuthenticatedFlowBuilderQrIdRouteImport.update({
    id: '/flow-builder/$qrId',
    path: '/flow-builder/$qrId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCheckoutPlanSlugRoute =
  AuthenticatedCheckoutPlanSlugRouteImport.update({
    id: '/checkout/$planSlug',
    path: '/checkout/$planSlug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnalyticsQrIdRoute =
  AuthenticatedAnalyticsQrIdRouteImport.update({
    id: '/$qrId',
    path: '/$qrId',
    getParentRoute: () => AuthenticatedAnalyticsRoute,
  } as any)
const AuthenticatedAdminPlansRoute = AuthenticatedAdminPlansRouteImport.update({
  id: '/admin/plans',
  path: '/admin/plans',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminAiRoute = AuthenticatedAdminAiRouteImport.update({
  id: '/admin/ai',
  path: '/admin/ai',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPontoWebauthnRegisterVerifyRoute =
  ApiPontoWebauthnRegisterVerifyRouteImport.update({
    id: '/api/ponto/webauthn/register-verify',
    path: '/api/ponto/webauthn/register-verify',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPontoWebauthnRegisterOptionsRoute =
  ApiPontoWebauthnRegisterOptionsRouteImport.update({
    id: '/api/ponto/webauthn/register-options',
    path: '/api/ponto/webauthn/register-options',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPontoWebauthnAuthVerifyRoute =
  ApiPontoWebauthnAuthVerifyRouteImport.update({
    id: '/api/ponto/webauthn/auth-verify',
    path: '/api/ponto/webauthn/auth-verify',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPontoWebauthnAuthOptionsRoute =
  ApiPontoWebauthnAuthOptionsRouteImport.update({
    id: '/api/ponto/webauthn/auth-options',
    path: '/api/ponto/webauthn/auth-options',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPontoAdminWebauthnClearRoute =
  ApiPontoAdminWebauthnClearRouteImport.update({
    id: '/api/ponto/admin/webauthn-clear',
    path: '/api/ponto/admin/webauthn-clear',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPontoAdminDeviceResetRoute =
  ApiPontoAdminDeviceResetRouteImport.update({
    id: '/api/ponto/admin/device-reset',
    path: '/api/ponto/admin/device-reset',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/analytics': typeof AuthenticatedAnalyticsRouteWithChildren
  '/billing': typeof AuthenticatedBillingRoute
  '/bulk': typeof AuthenticatedBulkRoute
  '/create': typeof AuthenticatedCreateRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/ponto': typeof AuthenticatedPontoRoute
  '/proofs': typeof AuthenticatedProofsRoute
  '/submissions': typeof AuthenticatedSubmissionsRoute
  '/ai/$shortId': typeof AiShortIdRoute
  '/f/$shortId': typeof FShortIdRoute
  '/links/$shortId': typeof LinksShortIdRoute
  '/ponto/$shortId': typeof PontoShortIdRoute
  '/proof/$id': typeof ProofIdRoute
  '/q/$shortId': typeof QShortIdRoute
  '/r/$shortId': typeof RShortIdRoute
  '/vcard/$shortId': typeof VcardShortIdRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/analytics/$qrId': typeof AuthenticatedAnalyticsQrIdRoute
  '/checkout/$planSlug': typeof AuthenticatedCheckoutPlanSlugRoute
  '/flow-builder/$qrId': typeof AuthenticatedFlowBuilderQrIdRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/mp/pix-checkout': typeof ApiMpPixCheckoutRoute
  '/api/mp/subscribe': typeof ApiMpSubscribeRoute
  '/api/mp/subscription': typeof ApiMpSubscriptionRoute
  '/api/mp/webhook': typeof ApiMpWebhookRoute
  '/api/ponto/punch': typeof ApiPontoPunchRoute
  '/api/ponto/resolve-pin': typeof ApiPontoResolvePinRoute
  '/api/public/scan': typeof ApiPublicScanRoute
  '/api/public/scanai': typeof ApiPublicScanaiRoute
  '/api/public/submit': typeof ApiPublicSubmitRoute
  '/api/public/verify-password': typeof ApiPublicVerifyPasswordRoute
  '/api/ponto/admin/device-reset': typeof ApiPontoAdminDeviceResetRoute
  '/api/ponto/admin/webauthn-clear': typeof ApiPontoAdminWebauthnClearRoute
  '/api/ponto/webauthn/auth-options': typeof ApiPontoWebauthnAuthOptionsRoute
  '/api/ponto/webauthn/auth-verify': typeof ApiPontoWebauthnAuthVerifyRoute
  '/api/ponto/webauthn/register-options': typeof ApiPontoWebauthnRegisterOptionsRoute
  '/api/ponto/webauthn/register-verify': typeof ApiPontoWebauthnRegisterVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/analytics': typeof AuthenticatedAnalyticsRouteWithChildren
  '/billing': typeof AuthenticatedBillingRoute
  '/bulk': typeof AuthenticatedBulkRoute
  '/create': typeof AuthenticatedCreateRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/plans': typeof AuthenticatedPlansRoute
  '/ponto': typeof AuthenticatedPontoRoute
  '/proofs': typeof AuthenticatedProofsRoute
  '/submissions': typeof AuthenticatedSubmissionsRoute
  '/ai/$shortId': typeof AiShortIdRoute
  '/f/$shortId': typeof FShortIdRoute
  '/links/$shortId': typeof LinksShortIdRoute
  '/ponto/$shortId': typeof PontoShortIdRoute
  '/proof/$id': typeof ProofIdRoute
  '/q/$shortId': typeof QShortIdRoute
  '/r/$shortId': typeof RShortIdRoute
  '/vcard/$shortId': typeof VcardShortIdRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/analytics/$qrId': typeof AuthenticatedAnalyticsQrIdRoute
  '/checkout/$planSlug': typeof AuthenticatedCheckoutPlanSlugRoute
  '/flow-builder/$qrId': typeof AuthenticatedFlowBuilderQrIdRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/mp/pix-checkout': typeof ApiMpPixCheckoutRoute
  '/api/mp/subscribe': typeof ApiMpSubscribeRoute
  '/api/mp/subscription': typeof ApiMpSubscriptionRoute
  '/api/mp/webhook': typeof ApiMpWebhookRoute
  '/api/ponto/punch': typeof ApiPontoPunchRoute
  '/api/ponto/resolve-pin': typeof ApiPontoResolvePinRoute
  '/api/public/scan': typeof ApiPublicScanRoute
  '/api/public/scanai': typeof ApiPublicScanaiRoute
  '/api/public/submit': typeof ApiPublicSubmitRoute
  '/api/public/verify-password': typeof ApiPublicVerifyPasswordRoute
  '/api/ponto/admin/device-reset': typeof ApiPontoAdminDeviceResetRoute
  '/api/ponto/admin/webauthn-clear': typeof ApiPontoAdminWebauthnClearRoute
  '/api/ponto/webauthn/auth-options': typeof ApiPontoWebauthnAuthOptionsRoute
  '/api/ponto/webauthn/auth-verify': typeof ApiPontoWebauthnAuthVerifyRoute
  '/api/ponto/webauthn/register-options': typeof ApiPontoWebauthnRegisterOptionsRoute
  '/api/ponto/webauthn/register-verify': typeof ApiPontoWebauthnRegisterVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRouteWithChildren
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/bulk': typeof AuthenticatedBulkRoute
  '/_authenticated/create': typeof AuthenticatedCreateRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/plans': typeof AuthenticatedPlansRoute
  '/_authenticated/ponto': typeof AuthenticatedPontoRoute
  '/_authenticated/proofs': typeof AuthenticatedProofsRoute
  '/_authenticated/submissions': typeof AuthenticatedSubmissionsRoute
  '/ai/$shortId': typeof AiShortIdRoute
  '/f/$shortId': typeof FShortIdRoute
  '/links/$shortId': typeof LinksShortIdRoute
  '/ponto/$shortId': typeof PontoShortIdRoute
  '/proof/$id': typeof ProofIdRoute
  '/q/$shortId': typeof QShortIdRoute
  '/r/$shortId': typeof RShortIdRoute
  '/vcard/$shortId': typeof VcardShortIdRoute
  '/_authenticated/admin/ai': typeof AuthenticatedAdminAiRoute
  '/_authenticated/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/_authenticated/analytics/$qrId': typeof AuthenticatedAnalyticsQrIdRoute
  '/_authenticated/checkout/$planSlug': typeof AuthenticatedCheckoutPlanSlugRoute
  '/_authenticated/flow-builder/$qrId': typeof AuthenticatedFlowBuilderQrIdRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/mp/pix-checkout': typeof ApiMpPixCheckoutRoute
  '/api/mp/subscribe': typeof ApiMpSubscribeRoute
  '/api/mp/subscription': typeof ApiMpSubscriptionRoute
  '/api/mp/webhook': typeof ApiMpWebhookRoute
  '/api/ponto/punch': typeof ApiPontoPunchRoute
  '/api/ponto/resolve-pin': typeof ApiPontoResolvePinRoute
  '/api/public/scan': typeof ApiPublicScanRoute
  '/api/public/scanai': typeof ApiPublicScanaiRoute
  '/api/public/submit': typeof ApiPublicSubmitRoute
  '/api/public/verify-password': typeof ApiPublicVerifyPasswordRoute
  '/api/ponto/admin/device-reset': typeof ApiPontoAdminDeviceResetRoute
  '/api/ponto/admin/webauthn-clear': typeof ApiPontoAdminWebauthnClearRoute
  '/api/ponto/webauthn/auth-options': typeof ApiPontoWebauthnAuthOptionsRoute
  '/api/ponto/webauthn/auth-verify': typeof ApiPontoWebauthnAuthVerifyRoute
  '/api/ponto/webauthn/register-options': typeof ApiPontoWebauthnRegisterOptionsRoute
  '/api/ponto/webauthn/register-verify': typeof ApiPontoWebauthnRegisterVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacidade'
    | '/termos'
    | '/analytics'
    | '/billing'
    | '/bulk'
    | '/create'
    | '/dashboard'
    | '/plans'
    | '/ponto'
    | '/proofs'
    | '/submissions'
    | '/ai/$shortId'
    | '/f/$shortId'
    | '/links/$shortId'
    | '/ponto/$shortId'
    | '/proof/$id'
    | '/q/$shortId'
    | '/r/$shortId'
    | '/vcard/$shortId'
    | '/admin/ai'
    | '/admin/plans'
    | '/analytics/$qrId'
    | '/checkout/$planSlug'
    | '/flow-builder/$qrId'
    | '/api/ai/chat'
    | '/api/mp/pix-checkout'
    | '/api/mp/subscribe'
    | '/api/mp/subscription'
    | '/api/mp/webhook'
    | '/api/ponto/punch'
    | '/api/ponto/resolve-pin'
    | '/api/public/scan'
    | '/api/public/scanai'
    | '/api/public/submit'
    | '/api/public/verify-password'
    | '/api/ponto/admin/device-reset'
    | '/api/ponto/admin/webauthn-clear'
    | '/api/ponto/webauthn/auth-options'
    | '/api/ponto/webauthn/auth-verify'
    | '/api/ponto/webauthn/register-options'
    | '/api/ponto/webauthn/register-verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacidade'
    | '/termos'
    | '/analytics'
    | '/billing'
    | '/bulk'
    | '/create'
    | '/dashboard'
    | '/plans'
    | '/ponto'
    | '/proofs'
    | '/submissions'
    | '/ai/$shortId'
    | '/f/$shortId'
    | '/links/$shortId'
    | '/ponto/$shortId'
    | '/proof/$id'
    | '/q/$shortId'
    | '/r/$shortId'
    | '/vcard/$shortId'
    | '/admin/ai'
    | '/admin/plans'
    | '/analytics/$qrId'
    | '/checkout/$planSlug'
    | '/flow-builder/$qrId'
    | '/api/ai/chat'
    | '/api/mp/pix-checkout'
    | '/api/mp/subscribe'
    | '/api/mp/subscription'
    | '/api/mp/webhook'
    | '/api/ponto/punch'
    | '/api/ponto/resolve-pin'
    | '/api/public/scan'
    | '/api/public/scanai'
    | '/api/public/submit'
    | '/api/public/verify-password'
    | '/api/ponto/admin/device-reset'
    | '/api/ponto/admin/webauthn-clear'
    | '/api/ponto/webauthn/auth-options'
    | '/api/ponto/webauthn/auth-verify'
    | '/api/ponto/webauthn/register-options'
    | '/api/ponto/webauthn/register-verify'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/privacidade'
    | '/termos'
    | '/_authenticated/analytics'
    | '/_authenticated/billing'
    | '/_authenticated/bulk'
    | '/_authenticated/create'
    | '/_authenticated/dashboard'
    | '/_authenticated/plans'
    | '/_authenticated/ponto'
    | '/_authenticated/proofs'
    | '/_authenticated/submissions'
    | '/ai/$shortId'
    | '/f/$shortId'
    | '/links/$shortId'
    | '/ponto/$shortId'
    | '/proof/$id'
    | '/q/$shortId'
    | '/r/$shortId'
    | '/vcard/$shortId'
    | '/_authenticated/admin/ai'
    | '/_authenticated/admin/plans'
    | '/_authenticated/analytics/$qrId'
    | '/_authenticated/checkout/$planSlug'
    | '/_authenticated/flow-builder/$qrId'
    | '/api/ai/chat'
    | '/api/mp/pix-checkout'
    | '/api/mp/subscribe'
    | '/api/mp/subscription'
    | '/api/mp/webhook'
    | '/api/ponto/punch'
    | '/api/ponto/resolve-pin'
    | '/api/public/scan'
    | '/api/public/scanai'
    | '/api/public/submit'
    | '/api/public/verify-password'
    | '/api/ponto/admin/device-reset'
    | '/api/ponto/admin/webauthn-clear'
    | '/api/ponto/webauthn/auth-options'
    | '/api/ponto/webauthn/auth-verify'
    | '/api/ponto/webauthn/register-options'
    | '/api/ponto/webauthn/register-verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
  AiShortIdRoute: typeof AiShortIdRoute
  FShortIdRoute: typeof FShortIdRoute
  LinksShortIdRoute: typeof LinksShortIdRoute
  PontoShortIdRoute: typeof PontoShortIdRoute
  ProofIdRoute: typeof ProofIdRoute
  QShortIdRoute: typeof QShortIdRoute
  RShortIdRoute: typeof RShortIdRoute
  VcardShortIdRoute: typeof VcardShortIdRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiMpPixCheckoutRoute: typeof ApiMpPixCheckoutRoute
  ApiMpSubscribeRoute: typeof ApiMpSubscribeRoute
  ApiMpSubscriptionRoute: typeof ApiMpSubscriptionRoute
  ApiMpWebhookRoute: typeof ApiMpWebhookRoute
  ApiPontoPunchRoute: typeof ApiPontoPunchRoute
  ApiPontoResolvePinRoute: typeof ApiPontoResolvePinRoute
  ApiPublicScanRoute: typeof ApiPublicScanRoute
  ApiPublicScanaiRoute: typeof ApiPublicScanaiRoute
  ApiPublicSubmitRoute: typeof ApiPublicSubmitRoute
  ApiPublicVerifyPasswordRoute: typeof ApiPublicVerifyPasswordRoute
  ApiPontoAdminDeviceResetRoute: typeof ApiPontoAdminDeviceResetRoute
  ApiPontoAdminWebauthnClearRoute: typeof ApiPontoAdminWebauthnClearRoute
  ApiPontoWebauthnAuthOptionsRoute: typeof ApiPontoWebauthnAuthOptionsRoute
  ApiPontoWebauthnAuthVerifyRoute: typeof ApiPontoWebauthnAuthVerifyRoute
  ApiPontoWebauthnRegisterOptionsRoute: typeof ApiPontoWebauthnRegisterOptionsRoute
  ApiPontoWebauthnRegisterVerifyRoute: typeof ApiPontoWebauthnRegisterVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vcard/$shortId': {
      id: '/vcard/$shortId'
      path: '/vcard/$shortId'
      fullPath: '/vcard/$shortId'
      preLoaderRoute: typeof VcardShortIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$shortId': {
      id: '/r/$shortId'
      path: '/r/$shortId'
      fullPath: '/r/$shortId'
      preLoaderRoute: typeof RShortIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q/$shortId': {
      id: '/q/$shortId'
      path: '/q/$shortId'
      fullPath: '/q/$shortId'
      preLoaderRoute: typeof QShortIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proof/$id': {
      id: '/proof/$id'
      path: '/proof/$id'
      fullPath: '/proof/$id'
      preLoaderRoute: typeof ProofIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ponto/$shortId': {
      id: '/ponto/$shortId'
      path: '/ponto/$shortId'
      fullPath: '/ponto/$shortId'
      preLoaderRoute: typeof PontoShortIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links/$shortId': {
      id: '/links/$shortId'
      path: '/links/$shortId'
      fullPath: '/links/$shortId'
      preLoaderRoute: typeof LinksShortIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$shortId': {
      id: '/f/$shortId'
      path: '/f/$shortId'
      fullPath: '/f/$shortId'
      preLoaderRoute: typeof FShortIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/$shortId': {
      id: '/ai/$shortId'
      path: '/ai/$shortId'
      fullPath: '/ai/$shortId'
      preLoaderRoute: typeof AiShortIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/submissions': {
      id: '/_authenticated/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof AuthenticatedSubmissionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/proofs': {
      id: '/_authenticated/proofs'
      path: '/proofs'
      fullPath: '/proofs'
      preLoaderRoute: typeof AuthenticatedProofsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ponto': {
      id: '/_authenticated/ponto'
      path: '/ponto'
      fullPath: '/ponto'
      preLoaderRoute: typeof AuthenticatedPontoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plans': {
      id: '/_authenticated/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AuthenticatedPlansRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/create': {
      id: '/_authenticated/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthenticatedCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bulk': {
      id: '/_authenticated/bulk'
      path: '/bulk'
      fullPath: '/bulk'
      preLoaderRoute: typeof AuthenticatedBulkRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/verify-password': {
      id: '/api/public/verify-password'
      path: '/api/public/verify-password'
      fullPath: '/api/public/verify-password'
      preLoaderRoute: typeof ApiPublicVerifyPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/submit': {
      id: '/api/public/submit'
      path: '/api/public/submit'
      fullPath: '/api/public/submit'
      preLoaderRoute: typeof ApiPublicSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scanai': {
      id: '/api/public/scanai'
      path: '/api/public/scanai'
      fullPath: '/api/public/scanai'
      preLoaderRoute: typeof ApiPublicScanaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scan': {
      id: '/api/public/scan'
      path: '/api/public/scan'
      fullPath: '/api/public/scan'
      preLoaderRoute: typeof ApiPublicScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ponto/resolve-pin': {
      id: '/api/ponto/resolve-pin'
      path: '/api/ponto/resolve-pin'
      fullPath: '/api/ponto/resolve-pin'
      preLoaderRoute: typeof ApiPontoResolvePinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ponto/punch': {
      id: '/api/ponto/punch'
      path: '/api/ponto/punch'
      fullPath: '/api/ponto/punch'
      preLoaderRoute: typeof ApiPontoPunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mp/webhook': {
      id: '/api/mp/webhook'
      path: '/api/mp/webhook'
      fullPath: '/api/mp/webhook'
      preLoaderRoute: typeof ApiMpWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mp/subscription': {
      id: '/api/mp/subscription'
      path: '/api/mp/subscription'
      fullPath: '/api/mp/subscription'
      preLoaderRoute: typeof ApiMpSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mp/subscribe': {
      id: '/api/mp/subscribe'
      path: '/api/mp/subscribe'
      fullPath: '/api/mp/subscribe'
      preLoaderRoute: typeof ApiMpSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mp/pix-checkout': {
      id: '/api/mp/pix-checkout'
      path: '/api/mp/pix-checkout'
      fullPath: '/api/mp/pix-checkout'
      preLoaderRoute: typeof ApiMpPixCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/flow-builder/$qrId': {
      id: '/_authenticated/flow-builder/$qrId'
      path: '/flow-builder/$qrId'
      fullPath: '/flow-builder/$qrId'
      preLoaderRoute: typeof AuthenticatedFlowBuilderQrIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/checkout/$planSlug': {
      id: '/_authenticated/checkout/$planSlug'
      path: '/checkout/$planSlug'
      fullPath: '/checkout/$planSlug'
      preLoaderRoute: typeof AuthenticatedCheckoutPlanSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics/$qrId': {
      id: '/_authenticated/analytics/$qrId'
      path: '/$qrId'
      fullPath: '/analytics/$qrId'
      preLoaderRoute: typeof AuthenticatedAnalyticsQrIdRouteImport
      parentRoute: typeof AuthenticatedAnalyticsRoute
    }
    '/_authenticated/admin/plans': {
      id: '/_authenticated/admin/plans'
      path: '/admin/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AuthenticatedAdminPlansRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/ai': {
      id: '/_authenticated/admin/ai'
      path: '/admin/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AuthenticatedAdminAiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/ponto/webauthn/register-verify': {
      id: '/api/ponto/webauthn/register-verify'
      path: '/api/ponto/webauthn/register-verify'
      fullPath: '/api/ponto/webauthn/register-verify'
      preLoaderRoute: typeof ApiPontoWebauthnRegisterVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ponto/webauthn/register-options': {
      id: '/api/ponto/webauthn/register-options'
      path: '/api/ponto/webauthn/register-options'
      fullPath: '/api/ponto/webauthn/register-options'
      preLoaderRoute: typeof ApiPontoWebauthnRegisterOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ponto/webauthn/auth-verify': {
      id: '/api/ponto/webauthn/auth-verify'
      path: '/api/ponto/webauthn/auth-verify'
      fullPath: '/api/ponto/webauthn/auth-verify'
      preLoaderRoute: typeof ApiPontoWebauthnAuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ponto/webauthn/auth-options': {
      id: '/api/ponto/webauthn/auth-options'
      path: '/api/ponto/webauthn/auth-options'
      fullPath: '/api/ponto/webauthn/auth-options'
      preLoaderRoute: typeof ApiPontoWebauthnAuthOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ponto/admin/webauthn-clear': {
      id: '/api/ponto/admin/webauthn-clear'
      path: '/api/ponto/admin/webauthn-clear'
      fullPath: '/api/ponto/admin/webauthn-clear'
      preLoaderRoute: typeof ApiPontoAdminWebauthnClearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ponto/admin/device-reset': {
      id: '/api/ponto/admin/device-reset'
      path: '/api/ponto/admin/device-reset'
      fullPath: '/api/ponto/admin/device-reset'
      preLoaderRoute: typeof ApiPontoAdminDeviceResetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAnalyticsRouteChildren {
  AuthenticatedAnalyticsQrIdRoute: typeof AuthenticatedAnalyticsQrIdRoute
}

const AuthenticatedAnalyticsRouteChildren: AuthenticatedAnalyticsRouteChildren =
  {
    AuthenticatedAnalyticsQrIdRoute: AuthenticatedAnalyticsQrIdRoute,
  }

const AuthenticatedAnalyticsRouteWithChildren =
  AuthenticatedAnalyticsRoute._addFileChildren(
    AuthenticatedAnalyticsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRouteWithChildren
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedBulkRoute: typeof AuthenticatedBulkRoute
  AuthenticatedCreateRoute: typeof AuthenticatedCreateRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPlansRoute: typeof AuthenticatedPlansRoute
  AuthenticatedPontoRoute: typeof AuthenticatedPontoRoute
  AuthenticatedProofsRoute: typeof AuthenticatedProofsRoute
  AuthenticatedSubmissionsRoute: typeof AuthenticatedSubmissionsRoute
  AuthenticatedAdminAiRoute: typeof AuthenticatedAdminAiRoute
  AuthenticatedAdminPlansRoute: typeof AuthenticatedAdminPlansRoute
  AuthenticatedCheckoutPlanSlugRoute: typeof AuthenticatedCheckoutPlanSlugRoute
  AuthenticatedFlowBuilderQrIdRoute: typeof AuthenticatedFlowBuilderQrIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRouteWithChildren,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedBulkRoute: AuthenticatedBulkRoute,
  AuthenticatedCreateRoute: AuthenticatedCreateRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPlansRoute: AuthenticatedPlansRoute,
  AuthenticatedPontoRoute: AuthenticatedPontoRoute,
  AuthenticatedProofsRoute: AuthenticatedProofsRoute,
  AuthenticatedSubmissionsRoute: AuthenticatedSubmissionsRoute,
  AuthenticatedAdminAiRoute: AuthenticatedAdminAiRoute,
  AuthenticatedAdminPlansRoute: AuthenticatedAdminPlansRoute,
  AuthenticatedCheckoutPlanSlugRoute: AuthenticatedCheckoutPlanSlugRoute,
  AuthenticatedFlowBuilderQrIdRoute: AuthenticatedFlowBuilderQrIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
  AiShortIdRoute: AiShortIdRoute,
  FShortIdRoute: FShortIdRoute,
  LinksShortIdRoute: LinksShortIdRoute,
  PontoShortIdRoute: PontoShortIdRoute,
  ProofIdRoute: ProofIdRoute,
  QShortIdRoute: QShortIdRoute,
  RShortIdRoute: RShortIdRoute,
  VcardShortIdRoute: VcardShortIdRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiMpPixCheckoutRoute: ApiMpPixCheckoutRoute,
  ApiMpSubscribeRoute: ApiMpSubscribeRoute,
  ApiMpSubscriptionRoute: ApiMpSubscriptionRoute,
  ApiMpWebhookRoute: ApiMpWebhookRoute,
  ApiPontoPunchRoute: ApiPontoPunchRoute,
  ApiPontoResolvePinRoute: ApiPontoResolvePinRoute,
  ApiPublicScanRoute: ApiPublicScanRoute,
  ApiPublicScanaiRoute: ApiPublicScanaiRoute,
  ApiPublicSubmitRoute: ApiPublicSubmitRoute,
  ApiPublicVerifyPasswordRoute: ApiPublicVerifyPasswordRoute,
  ApiPontoAdminDeviceResetRoute: ApiPontoAdminDeviceResetRoute,
  ApiPontoAdminWebauthnClearRoute: ApiPontoAdminWebauthnClearRoute,
  ApiPontoWebauthnAuthOptionsRoute: ApiPontoWebauthnAuthOptionsRoute,
  ApiPontoWebauthnAuthVerifyRoute: ApiPontoWebauthnAuthVerifyRoute,
  ApiPontoWebauthnRegisterOptionsRoute: ApiPontoWebauthnRegisterOptionsRoute,
  ApiPontoWebauthnRegisterVerifyRoute: ApiPontoWebauthnRegisterVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
