/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VcardShortIdRouteImport } from './routes/vcard.$shortId'
import { Route as RShortIdRouteImport } from './routes/r.$shortId'
import { Route as QShortIdRouteImport } from './routes/q.$shortId'
import { Route as ProofIdRouteImport } from './routes/proof.$id'
import { Route as LinksShortIdRouteImport } from './routes/links.$shortId'
import { Route as AiShortIdRouteImport } from './routes/ai.$shortId'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCreateRouteImport } from './routes/_authenticated/create'
import { Route as AuthenticatedBulkRouteImport } from './routes/_authenticated/bulk'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as ApiPublicScanaiRouteImport } from './routes/api/public/scanai'
import { Route as ApiPublicScanRouteImport } from './routes/api/public/scan'
import { Route as AuthenticatedAnalyticsQrIdRouteImport } from './routes/_authenticated/analytics.$qrId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VcardShortIdRoute = VcardShortIdRouteImport.update({
  id: '/vcard/$shortId',
  path: '/vcard/$shortId',
  getParentRoute: () => rootRouteImport,
} as any)
const RShortIdRoute = RShortIdRouteImport.update({
  id: '/r/$shortId',
  path: '/r/$shortId',
  getParentRoute: () => rootRouteImport,
} as any)
const QShortIdRoute = QShortIdRouteImport.update({
  id: '/q/$shortId',
  path: '/q/$shortId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofIdRoute = ProofIdRouteImport.update({
  id: '/proof/$id',
  path: '/proof/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksShortIdRoute = LinksShortIdRouteImport.update({
  id: '/links/$shortId',
  path: '/links/$shortId',
  getParentRoute: () => rootRouteImport,
} as any)
const AiShortIdRoute = AiShortIdRouteImport.update({
  id: '/ai/$shortId',
  path: '/ai/$shortId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCreateRoute = AuthenticatedCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBulkRoute = AuthenticatedBulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicScanaiRoute = ApiPublicScanaiRouteImport.update({
  id: '/api/public/scanai',
  path: '/api/public/scanai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicScanRoute = ApiPublicScanRouteImport.update({
  id: '/api/public/scan',
  path: '/api/public/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalyticsQrIdRoute =
  AuthenticatedAnalyticsQrIdRouteImport.update({
    id: '/$qrId',
    path: '/$qrId',
    getParentRoute: () => AuthenticatedAnalyticsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AuthenticatedAnalyticsRouteWithChildren
  '/bulk': typeof AuthenticatedBulkRoute
  '/create': typeof AuthenticatedCreateRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ai/$shortId': typeof AiShortIdRoute
  '/links/$shortId': typeof LinksShortIdRoute
  '/proof/$id': typeof ProofIdRoute
  '/q/$shortId': typeof QShortIdRoute
  '/r/$shortId': typeof RShortIdRoute
  '/vcard/$shortId': typeof VcardShortIdRoute
  '/analytics/$qrId': typeof AuthenticatedAnalyticsQrIdRoute
  '/api/public/scan': typeof ApiPublicScanRoute
  '/api/public/scanai': typeof ApiPublicScanaiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AuthenticatedAnalyticsRouteWithChildren
  '/bulk': typeof AuthenticatedBulkRoute
  '/create': typeof AuthenticatedCreateRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/ai/$shortId': typeof AiShortIdRoute
  '/links/$shortId': typeof LinksShortIdRoute
  '/proof/$id': typeof ProofIdRoute
  '/q/$shortId': typeof QShortIdRoute
  '/r/$shortId': typeof RShortIdRoute
  '/vcard/$shortId': typeof VcardShortIdRoute
  '/analytics/$qrId': typeof AuthenticatedAnalyticsQrIdRoute
  '/api/public/scan': typeof ApiPublicScanRoute
  '/api/public/scanai': typeof ApiPublicScanaiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRouteWithChildren
  '/_authenticated/bulk': typeof AuthenticatedBulkRoute
  '/_authenticated/create': typeof AuthenticatedCreateRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/ai/$shortId': typeof AiShortIdRoute
  '/links/$shortId': typeof LinksShortIdRoute
  '/proof/$id': typeof ProofIdRoute
  '/q/$shortId': typeof QShortIdRoute
  '/r/$shortId': typeof RShortIdRoute
  '/vcard/$shortId': typeof VcardShortIdRoute
  '/_authenticated/analytics/$qrId': typeof AuthenticatedAnalyticsQrIdRoute
  '/api/public/scan': typeof ApiPublicScanRoute
  '/api/public/scanai': typeof ApiPublicScanaiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/bulk'
    | '/create'
    | '/dashboard'
    | '/ai/$shortId'
    | '/links/$shortId'
    | '/proof/$id'
    | '/q/$shortId'
    | '/r/$shortId'
    | '/vcard/$shortId'
    | '/analytics/$qrId'
    | '/api/public/scan'
    | '/api/public/scanai'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/bulk'
    | '/create'
    | '/dashboard'
    | '/ai/$shortId'
    | '/links/$shortId'
    | '/proof/$id'
    | '/q/$shortId'
    | '/r/$shortId'
    | '/vcard/$shortId'
    | '/analytics/$qrId'
    | '/api/public/scan'
    | '/api/public/scanai'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/analytics'
    | '/_authenticated/bulk'
    | '/_authenticated/create'
    | '/_authenticated/dashboard'
    | '/ai/$shortId'
    | '/links/$shortId'
    | '/proof/$id'
    | '/q/$shortId'
    | '/r/$shortId'
    | '/vcard/$shortId'
    | '/_authenticated/analytics/$qrId'
    | '/api/public/scan'
    | '/api/public/scanai'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AiShortIdRoute: typeof AiShortIdRoute
  LinksShortIdRoute: typeof LinksShortIdRoute
  ProofIdRoute: typeof ProofIdRoute
  QShortIdRoute: typeof QShortIdRoute
  RShortIdRoute: typeof RShortIdRoute
  VcardShortIdRoute: typeof VcardShortIdRoute
  ApiPublicScanRoute: typeof ApiPublicScanRoute
  ApiPublicScanaiRoute: typeof ApiPublicScanaiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vcard/$shortId': {
      id: '/vcard/$shortId'
      path: '/vcard/$shortId'
      fullPath: '/vcard/$shortId'
      preLoaderRoute: typeof VcardShortIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$shortId': {
      id: '/r/$shortId'
      path: '/r/$shortId'
      fullPath: '/r/$shortId'
      preLoaderRoute: typeof RShortIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q/$shortId': {
      id: '/q/$shortId'
      path: '/q/$shortId'
      fullPath: '/q/$shortId'
      preLoaderRoute: typeof QShortIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proof/$id': {
      id: '/proof/$id'
      path: '/proof/$id'
      fullPath: '/proof/$id'
      preLoaderRoute: typeof ProofIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links/$shortId': {
      id: '/links/$shortId'
      path: '/links/$shortId'
      fullPath: '/links/$shortId'
      preLoaderRoute: typeof LinksShortIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/$shortId': {
      id: '/ai/$shortId'
      path: '/ai/$shortId'
      fullPath: '/ai/$shortId'
      preLoaderRoute: typeof AiShortIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/create': {
      id: '/_authenticated/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthenticatedCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bulk': {
      id: '/_authenticated/bulk'
      path: '/bulk'
      fullPath: '/bulk'
      preLoaderRoute: typeof AuthenticatedBulkRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/scanai': {
      id: '/api/public/scanai'
      path: '/api/public/scanai'
      fullPath: '/api/public/scanai'
      preLoaderRoute: typeof ApiPublicScanaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scan': {
      id: '/api/public/scan'
      path: '/api/public/scan'
      fullPath: '/api/public/scan'
      preLoaderRoute: typeof ApiPublicScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analytics/$qrId': {
      id: '/_authenticated/analytics/$qrId'
      path: '/$qrId'
      fullPath: '/analytics/$qrId'
      preLoaderRoute: typeof AuthenticatedAnalyticsQrIdRouteImport
      parentRoute: typeof AuthenticatedAnalyticsRoute
    }
  }
}

interface AuthenticatedAnalyticsRouteChildren {
  AuthenticatedAnalyticsQrIdRoute: typeof AuthenticatedAnalyticsQrIdRoute
}

const AuthenticatedAnalyticsRouteChildren: AuthenticatedAnalyticsRouteChildren =
  {
    AuthenticatedAnalyticsQrIdRoute: AuthenticatedAnalyticsQrIdRoute,
  }

const AuthenticatedAnalyticsRouteWithChildren =
  AuthenticatedAnalyticsRoute._addFileChildren(
    AuthenticatedAnalyticsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRouteWithChildren
  AuthenticatedBulkRoute: typeof AuthenticatedBulkRoute
  AuthenticatedCreateRoute: typeof AuthenticatedCreateRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRouteWithChildren,
  AuthenticatedBulkRoute: AuthenticatedBulkRoute,
  AuthenticatedCreateRoute: AuthenticatedCreateRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AiShortIdRoute: AiShortIdRoute,
  LinksShortIdRoute: LinksShortIdRoute,
  ProofIdRoute: ProofIdRoute,
  QShortIdRoute: QShortIdRoute,
  RShortIdRoute: RShortIdRoute,
  VcardShortIdRoute: VcardShortIdRoute,
  ApiPublicScanRoute: ApiPublicScanRoute,
  ApiPublicScanaiRoute: ApiPublicScanaiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
